# Generated by Django 4.2.21 on 2025-05-10 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gorev',
            name='aciklama',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gorev',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='harcama',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kilometrekaydi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surucu',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surucu',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='surucu',
            name='telefon',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='surucu',
            name='ad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='surucu',
            name='ehliyet_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='surucu',
            name='soyad',
            field=models.CharField(max_length=100),
        ),
    ]
