# Generated by Django 4.2.21 on 2025-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_arac_created_at_gorev_aciklama_gorev_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arac',
            options={'verbose_name': 'Araç', 'verbose_name_plural': 'Araçlar'},
        ),
        migrations.AlterModelOptions(
            name='gorev',
            options={'verbose_name': 'Görev', 'verbose_name_plural': 'Görevler'},
        ),
        migrations.AlterModelOptions(
            name='harcama',
            options={'verbose_name': 'Harcama', 'verbose_name_plural': 'Harcamalar'},
        ),
        migrations.AlterModelOptions(
            name='kilometrekaydi',
            options={'verbose_name': 'Kilometre Kaydı', 'verbose_name_plural': 'Kilometre Kayıtları'},
        ),
        migrations.AlterModelOptions(
            name='surucu',
            options={'verbose_name': 'Sürücü', 'verbose_name_plural': 'Sürücüler'},
        ),
        migrations.AlterField(
            model_name='arac',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gorev',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='harcama',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kilometrekaydi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='surucu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
